/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import creditospce.qnaDependencias;
import java.awt.Container;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.GridLayout;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;

/**
 *
 * @author Juan
 */
public class frmAltaCalendarioProc extends javax.swing.JDialog {
    private final GridLayout esquema1;
    private final  GridBagLayout esquema2;
    private int Dependencia;
    private panelAltaQna[] ALTAQna;
    /**
     * Creates new form frmAltaCalendarioProc
     */
    public frmAltaCalendarioProc(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        esquema1 = new GridLayout(0,1);
        esquema2 = new GridBagLayout();
        GridBagConstraints constraints = new GridBagConstraints();
        initComponents();
        ALTAQna = new panelAltaQna[24];
        panelQnas.setLayout(esquema1);
        for ( int cuenta = 0; cuenta < 24; cuenta++ ) {
            ALTAQna[ cuenta ] = new panelAltaQna();
            ALTAQna[ cuenta ].setNQna(cuenta+1);
            panelQnas.add( ALTAQna[cuenta]); 
        }
        JScrollPane scrollpane = new JScrollPane(panelQnas);
        Container contenedor = getContentPane();
        contenedor.setLayout( esquema2 );
         constraints.gridx = 0;
         constraints.gridy = 0;
         constraints.gridwidth = 1;
         constraints.gridheight = 1;
         constraints.weighty = 0.0;
         constraints.fill = GridBagConstraints.HORIZONTAL;
        contenedor.add( panelControles, constraints );
         constraints.gridx = 0;
         constraints.gridy = 1;
         constraints.gridwidth = 1;
         constraints.gridheight = 1;
         constraints.weighty = 1.0;
         constraints.fill = GridBagConstraints.BOTH;        
        contenedor.add( scrollpane, constraints );
         constraints.gridx = 0;
         constraints.gridy =2;
         constraints.gridwidth = 1;
         constraints.gridheight = 1;
         constraints.weighty = 0.0;
         constraints.fill = GridBagConstraints.HORIZONTAL;
        contenedor.add( panelBotones, constraints );
        setSize( 1200, 700 );
        setVisible( true );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelControles = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbxDependencias = new javax.swing.JComboBox();
        panelQnas = new javax.swing.JPanel();
        panelBotones = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelControles.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelControles.setMaximumSize(new java.awt.Dimension(726, 46));
        panelControles.setMinimumSize(new java.awt.Dimension(726, 46));

        jLabel1.setText("Dependencia:");

        cbxDependencias.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "PODER EJECUTIVO", "PODER LEGISLATIVO", "PODER JUDICIAL", "MAGISTERIO", "JUBILADOS Y PENSIONADOS", "PENSIONES CIVILES DEL ESTADO DE TLAXCALA", "MUNICIPIO DE TLAXCALA", "MUNICIPIO DE CHIAUTEMPAN", "MUNICIPIO DE APETATITLAN", "CAPAM", "DIF TLAXCALA", "MUNICIPIO JUAN CUAMATZI", "MUNICIPIO DE TEPEYANCO", "MUNICIPO DE ANTONIO CARBAJAL" }));
        cbxDependencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxDependenciasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelControlesLayout = new javax.swing.GroupLayout(panelControles);
        panelControles.setLayout(panelControlesLayout);
        panelControlesLayout.setHorizontalGroup(
            panelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelControlesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addComponent(cbxDependencias, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(212, 212, 212))
        );
        panelControlesLayout.setVerticalGroup(
            panelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelControlesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbxDependencias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        panelQnas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelQnas.setMaximumSize(new java.awt.Dimension(960, 405));
        panelQnas.setMinimumSize(new java.awt.Dimension(960, 405));

        javax.swing.GroupLayout panelQnasLayout = new javax.swing.GroupLayout(panelQnas);
        panelQnas.setLayout(panelQnasLayout);
        panelQnasLayout.setHorizontalGroup(
            panelQnasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 956, Short.MAX_VALUE)
        );
        panelQnasLayout.setVerticalGroup(
            panelQnasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 401, Short.MAX_VALUE)
        );

        panelBotones.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelBotones.setMaximumSize(new java.awt.Dimension(961, 104));
        panelBotones.setMinimumSize(new java.awt.Dimension(961, 104));

        btnGuardar.setText("GUARDAR");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBotonesLayout = new javax.swing.GroupLayout(panelBotones);
        panelBotones.setLayout(panelBotonesLayout);
        panelBotonesLayout.setHorizontalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesLayout.createSequentialGroup()
                .addGap(377, 377, 377)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(414, Short.MAX_VALUE))
        );
        panelBotonesLayout.setVerticalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelQnas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelControles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(panelControles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelQnas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxDependenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxDependenciasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxDependenciasActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
    int Depen;
    qnaDependencias qnaD;
    Date FIniProc;
    Date FFinProc;
    Date FPago;
    Date FEnvio;
    Date FRecibo;  
        Dependencia=cbxDependencias.getSelectedIndex();
        for ( int cuenta = 0; cuenta < 24; cuenta++ ) {
            
            FIniProc=ALTAQna[ cuenta ].getFIniProc();
            FFinProc=ALTAQna[ cuenta ].getFFinProc();
            FEnvio=ALTAQna[ cuenta ].getFEnvio();
            FRecibo=ALTAQna[ cuenta ].getFRecibimos();
            FPago=ALTAQna[ cuenta ].getFPago();
            qnaD=new qnaDependencias(Dependencia,cuenta+1,FIniProc,FFinProc,FPago,FEnvio,FRecibo);
            qnaD.guardaQnaDependencias();
        }    
        JOptionPane.showMessageDialog(null, "EL CALENDARIO HA SIDO GUARDADO");
    }//GEN-LAST:event_btnGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAltaCalendarioProc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAltaCalendarioProc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAltaCalendarioProc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAltaCalendarioProc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmAltaCalendarioProc dialog = new frmAltaCalendarioProc(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox cbxDependencias;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelControles;
    private javax.swing.JPanel panelQnas;
    // End of variables declaration//GEN-END:variables
}
