/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import creditospce.credito;
import creditospce.empleadoBanco;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Juan
 */
public class frmCreditoBanco extends javax.swing.JDialog {
    private int TIPOCREDITO;
    private int ANO;
    private int NCREDITO;
    private Date FSOLICITUD=new Date();
    private boolean FLAG=false;
    private int BANCO;
    private String CLABE;
    private int IDEMPLEADO;
    /**
     * Creates new form frmCreditoBanco
     */
    public frmCreditoBanco(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();    
        this.TIPOCREDITO=0;
        this.ANO=0;
        this.NCREDITO=0;
        FSOLICITUD=dateChooserCombo1.getCurrent().getTime();
        CLABE="";
        BANCO=99;
        IDEMPLEADO=0;
    }
    
    public void setCredito(int IDEMPLEADO,int TIPOCREDITO, int ANO, int NCREDITO)
    {
        this.IDEMPLEADO=IDEMPLEADO;
        this.TIPOCREDITO=TIPOCREDITO;
        this.ANO=ANO;
        this.NCREDITO=NCREDITO; 
        String vCveC="V-";
        if (TIPOCREDITO==0){vCveC="V-";}
        if (TIPOCREDITO==1){vCveC="R-";}
        if (TIPOCREDITO==2){vCveC="H-";}
        vCveC=vCveC+String.valueOf(ANO)+"-"+String.format("%05d",NCREDITO);
        txtCredito.setText(vCveC); 
    }
    
    public void setEmpleadoBanco(int BANCO, String CLABE)
    {
        this.BANCO=BANCO;
        this.CLABE=CLABE;
        txtCLABE.setText(CLABE);
        cbxBancos.setSelectedIndex(BANCO);
        txtCLABE.setEnabled(false);
        cbxBancos.setEnabled(false);
    }
    public boolean getFlag()
    {    
        return FLAG;
    }
    
    public boolean cierra()
    {
        boolean flag=true;
        dispose();
        return flag;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateChooserCombo1 = new datechooser.beans.DateChooserCombo();
        cbxBancos = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCredito = new javax.swing.JTextField();
        txtCLABE = new javax.swing.JTextField();
        btnGUARDAR = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtCuenta = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        dateChooserCombo1.setCurrentView(new datechooser.view.appearance.AppearancesList("Bordered",
            new datechooser.view.appearance.ViewAppearance("custom",
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    true,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 255),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(128, 128, 128),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(255, 0, 0),
                    false,
                    false,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                (datechooser.view.BackRenderer)null,
                false,
                true)));
    dateChooserCombo1.addCommitListener(new datechooser.events.CommitListener() {
        public void onCommit(datechooser.events.CommitEvent evt) {
            dateChooserCombo1OnCommit(evt);
        }
    });

    cbxBancos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "BBVA BANCOMER", "BANAMEX", "HSBC", "SANTANDER", "SCOTIABANK", "BANCO AZTECA", "BANORTE", "BANCO INBURSA", "BANCO DEL BAJIO", "IXE BANCO", "BANCA MIFEL", "BANCO ACTINVER", " " }));

    jLabel2.setText("BANCO:");

    jLabel3.setText("CLABE:");

    jLabel4.setText("F. DE DISPERCION:");

    txtCredito.setEditable(false);

    txtCLABE.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusLost(java.awt.event.FocusEvent evt) {
            txtCLABEFocusLost(evt);
        }
    });
    txtCLABE.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyTyped(java.awt.event.KeyEvent evt) {
            txtCLABEKeyTyped(evt);
        }
        public void keyPressed(java.awt.event.KeyEvent evt) {
            txtCLABEKeyPressed(evt);
        }
    });

    btnGUARDAR.setText("GUARDAR");
    btnGUARDAR.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnGUARDARActionPerformed(evt);
        }
    });

    jLabel1.setText("CREDITO:");

    txtCuenta.setEditable(false);
    txtCuenta.setEnabled(false);
    txtCuenta.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusLost(java.awt.event.FocusEvent evt) {
            txtCuentaFocusLost(evt);
        }
    });
    txtCuenta.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyTyped(java.awt.event.KeyEvent evt) {
            txtCuentaKeyTyped(evt);
        }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGap(27, 27, 27)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel1)
                .addComponent(jLabel2)
                .addComponent(jLabel4)
                .addComponent(jLabel3))
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(txtCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(txtCLABE, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(cbxBancos, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(dateChooserCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(txtCredito, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createSequentialGroup()
                    .addGap(8, 8, 8)
                    .addComponent(btnGUARDAR, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap(46, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGap(22, 22, 22)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1)
                .addComponent(txtCredito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(cbxBancos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel2))
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel3)
                .addComponent(txtCLABE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
            .addComponent(txtCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel4)
                .addComponent(dateChooserCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(29, 29, 29)
            .addComponent(btnGUARDAR)
            .addGap(31, 31, 31))
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dateChooserCombo1OnCommit(datechooser.events.CommitEvent evt) {//GEN-FIRST:event_dateChooserCombo1OnCommit
        // TODO add your handling code here:
        //String fecha1=new SimpleDateFormat("dd/MM/yyyy").format(dateChooserCombo1.getCurrent().getTime());
        FSOLICITUD=dateChooserCombo1.getCurrent().getTime();
        //jLabel1.setText(fecha1);
    }//GEN-LAST:event_dateChooserCombo1OnCommit

    private void btnGUARDARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGUARDARActionPerformed
        // TODO add your handling code here:
        if(!"".equals(txtCLABE.getText())&&((txtCLABE.getText().length()==11)||(txtCLABE.getText().length()==18)))
        {
            credito cfechad= new credito();
            BANCO=cbxBancos.getSelectedIndex();
            empleadoBanco eBanco= new empleadoBanco();
            eBanco.setEpleadoBanco(IDEMPLEADO, CLABE, BANCO);
            eBanco.capturaBanco();
            cfechad.dispersaCredito(TIPOCREDITO, ANO, NCREDITO, FSOLICITUD, 5); //ESTATUS DISPERSIÓ
            
            FLAG=true;
            dispose();             
        }
    }//GEN-LAST:event_btnGUARDARActionPerformed

    private void txtCLABEFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCLABEFocusLost
        // TODO add your handling code here:
        if (txtCLABE.getText().length()==18)
        {
            String cuenta = txtCLABE.getText().substring(6,17);
            txtCuenta.setText(cuenta);    
            CLABE=txtCLABE.getText();
        }
        if ((txtCLABE.getText().length()!=11)&&(txtCLABE.getText().length()!=18))
        {
            JOptionPane.showMessageDialog(null, "LA CLABE BANCARIA DEBE SER NUMERICA DE 18 DÍGITOS Ó EL NÚMERO DE CUENTA DE 11 DÍGITOS");
            txtCuenta.requestFocusInWindow();       
        }
        if (txtCLABE.getText().length()==11)
        {
            txtCuenta.setText(txtCLABE.getText());    
            CLABE=txtCLABE.getText();
        } 
    }//GEN-LAST:event_txtCLABEFocusLost

    private void txtCLABEKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCLABEKeyPressed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_txtCLABEKeyPressed

    private void txtCLABEKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCLABEKeyTyped
        // TODO add your handling code here:
      char caracter = evt.getKeyChar();
      // Verificar si la tecla pulsada no es un digito
      if(((caracter < '0') ||
         (caracter > '9')) &&
         (caracter != '\b' /*corresponde a BACK_SPACE*/))
      {
         evt.consume();  // ignorar el evento de teclado
         getToolkit().beep(); 
      }
    }//GEN-LAST:event_txtCLABEKeyTyped

    private void txtCuentaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCuentaFocusLost
        // TODO add your handling code here:
       
    }//GEN-LAST:event_txtCuentaFocusLost

    private void txtCuentaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCuentaKeyTyped
        // TODO add your handling code here:
      char caracter = evt.getKeyChar();
      // Verificar si la tecla pulsada no es un digito
      if(((caracter < '0') ||
         (caracter > '9')) &&
         (caracter != '\b' /*corresponde a BACK_SPACE*/))
      {
         evt.consume();  // ignorar el evento de teclado
         getToolkit().beep(); 
      }
    }//GEN-LAST:event_txtCuentaKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCreditoBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCreditoBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCreditoBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCreditoBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmCreditoBanco dialog = new frmCreditoBanco(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGUARDAR;
    private javax.swing.JComboBox cbxBancos;
    private datechooser.beans.DateChooserCombo dateChooserCombo1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtCLABE;
    private javax.swing.JTextField txtCredito;
    private javax.swing.JTextField txtCuenta;
    // End of variables declaration//GEN-END:variables
}
