/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.aportaciones;
import controlador.listaAportacionesCalendario;
import controlador.listaAportacionesContables;
import creditospce.credito;
import creditospce.empleado;
import java.awt.BorderLayout;
import java.awt.Container;
import java.awt.GridLayout;
import java.text.SimpleDateFormat;
import java.util.LinkedList;
import java.util.ListIterator;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;

/**
 *
 * @author Juan
 */
public class frmCalendario extends javax.swing.JDialog {
    private credito CREDITO;
    private empleado EMPLEADO;
    private final GridLayout esquema;      
    private final GridLayout esquema1;
    /**
     * Creates new form frmCalendario
     */
    public frmCalendario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        esquema = new GridLayout(0,1); // espacios libres de 5 píxeles        
        esquema1 = new GridLayout(0,1);
        PACreditos.setLayout(esquema1);
        CREDITO= new credito();
        EMPLEADO= new empleado();
        Container contenedor = getContentPane();
        this.getContentPane().setLayout(esquema);
        this.getContentPane().add(PDTrabajador);
        this.getContentPane().add(PDCredito);
        contenedor.setLayout( esquema1 );
      JScrollPane scrollpane = new JScrollPane(PACreditos);
      contenedor.add( scrollpane, BorderLayout.CENTER ); 
        this.getContentPane().add(scrollpane);
      setSize( 1000, 500 );
      setVisible( true );        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PDTrabajador = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        cbxPrestamo = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        cbxAno = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        txtNCredito = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        PDCredito = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDatosCredito = new javax.swing.JTextArea();
        PACreditos = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        PDTrabajador.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel13.setText("PRESTAMO:");

        cbxPrestamo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CREDITO VERDE", "CREDITO ROJO", "CREDITO HIPOTECARIO" }));
        cbxPrestamo.setName(""); // NOI18N
        cbxPrestamo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxPrestamoItemStateChanged(evt);
            }
        });
        cbxPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxPrestamoActionPerformed(evt);
            }
        });
        cbxPrestamo.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cbxPrestamoPropertyChange(evt);
            }
        });

        jLabel1.setText("AÑO:");

        cbxAno.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2013", "2014" }));

        jLabel2.setText("N. CREDITO:");

        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PDTrabajadorLayout = new javax.swing.GroupLayout(PDTrabajador);
        PDTrabajador.setLayout(PDTrabajadorLayout);
        PDTrabajadorLayout.setHorizontalGroup(
            PDTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PDTrabajadorLayout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbxAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNCredito, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(btnBuscar)
                .addContainerGap(210, Short.MAX_VALUE))
        );
        PDTrabajadorLayout.setVerticalGroup(
            PDTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PDTrabajadorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PDTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(cbxPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(cbxAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtNCredito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PDCredito.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtDatosCredito.setColumns(20);
        txtDatosCredito.setRows(5);
        jScrollPane2.setViewportView(txtDatosCredito);

        javax.swing.GroupLayout PDCreditoLayout = new javax.swing.GroupLayout(PDCredito);
        PDCredito.setLayout(PDCreditoLayout);
        PDCreditoLayout.setHorizontalGroup(
            PDCreditoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PDCreditoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        PDCreditoLayout.setVerticalGroup(
            PDCreditoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PDCreditoLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                .addContainerGap())
        );

        PACreditos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout PACreditosLayout = new javax.swing.GroupLayout(PACreditos);
        PACreditos.setLayout(PACreditosLayout);
        PACreditosLayout.setHorizontalGroup(
            PACreditosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1030, Short.MAX_VALUE)
        );
        PACreditosLayout.setVerticalGroup(
            PACreditosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 353, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PDTrabajador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PACreditos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PDCredito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PDTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PDCredito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PACreditos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxPrestamoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxPrestamoItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxPrestamoItemStateChanged

    private void cbxPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxPrestamoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxPrestamoActionPerformed

    private void cbxPrestamoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cbxPrestamoPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxPrestamoPropertyChange

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        aportaciones aportacion=new aportaciones();
        PACreditos.removeAll();
        PACreditos.repaint();
        int IdCredito=0, ano=0, NCredito=0, NAportaciones=0;
        IdCredito=cbxPrestamo.getSelectedIndex();
        String A=(String) cbxAno.getSelectedItem();
        ano=Integer.parseInt(A);
        NCredito=Integer.parseInt(txtNCredito.getText());
        txtDatosCredito.setText(" ");
        if (txtNCredito.getText().isEmpty()==false)
        {

            //verifica que exista el credito
            if(CREDITO.existeCredito(IdCredito, ano, NCredito))
            {
                //se busca el creditos
                CREDITO.consultaCredito(IdCredito, ano, NCredito);
                EMPLEADO.consutlaEmpleadoID(CREDITO.IdEmpleado);
                Object datos[]=new Object[7];
                String cveCredito=" ", estatus="";
                SimpleDateFormat sdf=new java.text.SimpleDateFormat("dd/MM/yyyy");
                //DESPLIEGA LOS CREDITOS
                if (CREDITO.IdCredito==0) {cveCredito="V-";}
                if (CREDITO.IdCredito==1) {cveCredito="R-";}
                if (CREDITO.IdCredito==2) {cveCredito="H-";}
                //clave de estatus
                if (CREDITO.Estatus==0) {estatus="PENDIENTE";}
                if (CREDITO.Estatus==1) {estatus="ACTIVO";}
                if (CREDITO.Estatus==2) {estatus="PAGADO";}
                if (CREDITO.Estatus==3) {estatus="CANCELADO";}
                if (CREDITO.Estatus==4) {estatus="TODOS";}
                if (CREDITO.Estatus==5) {estatus="DISPERSADO";}
                if (CREDITO.Estatus==6) {estatus="COBRANDO";}
                cveCredito=cveCredito+String.valueOf(CREDITO.ano)+"-"+String.valueOf(CREDITO.NCredito);
                //numeroAportacionesIDAfil(int IDAfil, int idcredito, int ano, int ncredito)
                NAportaciones=aportacion.numeroAportacionesIDAfil(EMPLEADO.IdAfil, CREDITO.IdCredito, CREDITO.ano, CREDITO.NCredito);
                txtDatosCredito.append("Credito: "+cveCredito+"\t Estatus: "+estatus+"\n");
                txtDatosCredito.append("Monto del Prestamo: "+CREDITO.Montoa+"\t Aportación Quincenal: "+CREDITO.Aportacion+"\t Número De Aportaciones"+String.valueOf(NAportaciones)+"\n");
                txtDatosCredito.append("Fecha de Captura: "+sdf.format(CREDITO.FCaptura)+"\t Fecha de Disperción: "+sdf.format(CREDITO.FDispercion)+"\n");
                txtDatosCredito.append("ID: "+String.valueOf(EMPLEADO.IdAfil)+" : "+EMPLEADO.Nombres+" "+EMPLEADO.Paterno+" "+EMPLEADO.Materno );

                LinkedList<listaAportacionesCalendario> lAportaciones;// =new LinkedList<listaAportacionesContables>();
                listaAportacionesCalendario lAp = new listaAportacionesCalendario();
                lAportaciones=aportacion.reportaAportacionesCredito(IdCredito, ano, NCredito);
                ListIterator it;
                int nA=lAportaciones.size();
                panelCalendario[] panelC = new panelCalendario[nA];
                it=lAportaciones.listIterator();
                int nI=0;
                while (it.hasNext())
                    {
                        
                        lAp=(listaAportacionesCalendario)it.next();
                        // panelCalendario(int NA, String QNA, Double MI, Double MF, Double AQ, Double AC, Double AI, Double AA )
                        panelC[nI]=new panelCalendario(lAp.nAportacion,lAp.Quincena,lAp.montoInicial,lAp.montoFinal,lAp.pagoQ,lAp.pagoCapital,lAp.pagoInteres,0.0);
                        PACreditos.add(panelC[nI]);
                    }
            }
            //no existe el afiliado
            else
            {
                JOptionPane.showMessageDialog(null, "NO EXISTE ESE CREDITO");
            }
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCalendario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCalendario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCalendario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCalendario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmCalendario dialog = new frmCalendario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PACreditos;
    private javax.swing.JPanel PDCredito;
    private javax.swing.JPanel PDTrabajador;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JComboBox cbxAno;
    private javax.swing.JComboBox cbxPrestamo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtDatosCredito;
    private javax.swing.JTextField txtNCredito;
    // End of variables declaration//GEN-END:variables
}
