/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import creditospce.credito;
import creditospce.creditoReporte;
import java.awt.BorderLayout;
import java.awt.Container;
import java.awt.GridLayout;
import javax.swing.JScrollPane;

/**
 *
 * @author Juan
 */
public class frmCDispersion extends javax.swing.JFrame {
    private final BorderLayout esquema;    
    private final GridLayout esquema1;

    /**
     * Creates new form frmCDispersion
     */
    public frmCDispersion() {
        super( "DATOS DE DISPERSIÓN BANCARIA" );
        esquema = new BorderLayout( 5, 5 ); // espacios libres de 5 píxeles
        esquema1 = new GridLayout(0,1);
        initComponents();
        creditoReporte[] ACReditos;
        credito nc = new credito();
        ACReditos=nc.consultaCreditosEstatus(1);
        PestatusCredito[] panelEC = new PestatusCredito[ACReditos.length];
        pnlCreditos.setLayout(esquema1);
       for ( int cuenta = 0; cuenta < ACReditos.length; cuenta++ ) {
         panelEC[ cuenta ] = new PestatusCredito(ACReditos[cuenta].IdEmpleado, ACReditos[cuenta].IdCredito,ACReditos[cuenta].ano,ACReditos[cuenta].NCredito,ACReditos[cuenta].Montoa,ACReditos[cuenta].paterno,ACReditos[cuenta].materno,ACReditos[cuenta].nombre,ACReditos[cuenta].FCaptura,ACReditos[cuenta].FValidacion);
         pnlCreditos.add( panelEC[cuenta]); 
      }  
       JScrollPane scrollpane = new JScrollPane(pnlCreditos);
      // obtener panel de contenido y establecer su esquema
      Container contenedor = getContentPane();
      contenedor.setLayout( esquema );
      contenedor.add( scrollpane, BorderLayout.CENTER ); 
      setSize( 1000, 500 );
      setVisible( true );
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCreditos = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        javax.swing.GroupLayout pnlCreditosLayout = new javax.swing.GroupLayout(pnlCreditos);
        pnlCreditos.setLayout(pnlCreditosLayout);
        pnlCreditosLayout.setHorizontalGroup(
            pnlCreditosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 940, Short.MAX_VALUE)
        );
        pnlCreditosLayout.setVerticalGroup(
            pnlCreditosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 106, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(pnlCreditos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(138, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlCreditos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(378, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        //lee todos los creditos de la quincena que no han sido dispersados, 
        //o no se les ha capturado su fecha de ispercion
        
        //despues crea un un arreglo de clase de panel PestatusCredito
        
        //constructor con los datos de cada credito        
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCDispersion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCDispersion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCDispersion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCDispersion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCDispersion().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pnlCreditos;
    // End of variables declaration//GEN-END:variables
}
