/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import vista.frmAltaCalendarioProc;
import vista.frmReportesRH;

/**
 *
 * @author Juan
 */
public class frmPrincipal extends javax.swing.JFrame {
    public Integer IdCapturista=0;
    private frmCDispersion fDisp;
    private frmReportesRH fNew;
    private capturaCredito vCC;
    private frmContabilidad fConta;
    private frmEstadoCredito fECredito;
    //en cuanto se pase a dialog se quita la bandera
    private boolean flagfDisp=false;
    private boolean flagvCC=false;
    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal() {
        super( "SISTEMA DE GESTIÓN Y CONTROL DE CREDITOS" );
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        menuCapturaC = new javax.swing.JMenu();
        menuIAlta = new javax.swing.JMenuItem();
        menuIBaja = new javax.swing.JMenuItem();
        menuICambio = new javax.swing.JMenuItem();
        menuIConsulta = new javax.swing.JMenuItem();
        menuContabilidad = new javax.swing.JMenu();
        menuIDispersion = new javax.swing.JMenuItem();
        menuReportes = new javax.swing.JMenu();
        menuINuevos = new javax.swing.JMenuItem();
        menuAportaciones = new javax.swing.JMenuItem();
        menuCalendario = new javax.swing.JMenuItem();
        menuMonitor = new javax.swing.JMenuItem();
        menuCapturados = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        menuIAfectaciones = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuCapturaC.setText("CREDITO");
        menuCapturaC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuCapturaCMouseClicked(evt);
            }
        });
        menuCapturaC.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                menuCapturaCMenuSelected(evt);
            }
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
        });
        menuCapturaC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCapturaCActionPerformed(evt);
            }
        });

        menuIAlta.setText("ALTA");
        menuIAlta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuIAltaMouseClicked(evt);
            }
        });
        menuIAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuIAltaActionPerformed(evt);
            }
        });
        menuCapturaC.add(menuIAlta);

        menuIBaja.setText("BAJA");
        menuCapturaC.add(menuIBaja);

        menuICambio.setText("CAMBIO");
        menuCapturaC.add(menuICambio);

        menuIConsulta.setText("CONSULTA");
        menuIConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuIConsultaActionPerformed(evt);
            }
        });
        menuCapturaC.add(menuIConsulta);

        jMenuBar1.add(menuCapturaC);

        menuContabilidad.setText("ESTATUS");

        menuIDispersion.setText("DISPERSIÓN");
        menuIDispersion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuIDispersionActionPerformed(evt);
            }
        });
        menuContabilidad.add(menuIDispersion);

        jMenuBar1.add(menuContabilidad);

        menuReportes.setText("REPORTES");

        menuINuevos.setText("NUEVOS");
        menuINuevos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuINuevosActionPerformed(evt);
            }
        });
        menuReportes.add(menuINuevos);

        menuAportaciones.setText("APORTACIONES");
        menuAportaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAportacionesActionPerformed(evt);
            }
        });
        menuReportes.add(menuAportaciones);

        menuCalendario.setText("CALENDARIO");
        menuCalendario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCalendarioActionPerformed(evt);
            }
        });
        menuReportes.add(menuCalendario);

        menuMonitor.setText("MONITOR");
        menuMonitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMonitorActionPerformed(evt);
            }
        });
        menuReportes.add(menuMonitor);

        menuCapturados.setText("CAPTURADOS");
        menuCapturados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCapturadosActionPerformed(evt);
            }
        });
        menuReportes.add(menuCapturados);

        jMenuBar1.add(menuReportes);

        jMenu1.setText("CONTABILIDAD");

        menuIAfectaciones.setText("AFECTACIONES");
        menuIAfectaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuIAfectacionesActionPerformed(evt);
            }
        });
        jMenu1.add(menuIAfectaciones);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 770, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 313, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuCapturaCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCapturaCActionPerformed
        // TODO add your handling code here:         
    }//GEN-LAST:event_menuCapturaCActionPerformed

    private void menuCapturaCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuCapturaCMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_menuCapturaCMouseClicked

    private void menuCapturaCMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_menuCapturaCMenuSelected
        // TODO add your handling code here:      
    }//GEN-LAST:event_menuCapturaCMenuSelected

    private void menuIAfectacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuIAfectacionesActionPerformed
        // TODO add your handling code here:
        fConta = new frmContabilidad(this,false);
        fConta.setDefaultCloseOperation(frmContabilidad.DISPOSE_ON_CLOSE);
        fConta.setVisible(true);        
        
    }//GEN-LAST:event_menuIAfectacionesActionPerformed

    private void menuIAltaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuIAltaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_menuIAltaMouseClicked

    private void menuIAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuIAltaActionPerformed
        // TODO add your handling code here:
                    vCC = new capturaCredito();
                    vCC.setDefaultCloseOperation(capturaCredito.DISPOSE_ON_CLOSE );
                    vCC.IdCapturista=IdCapturista;
                    vCC.setVisible(true);         
    }//GEN-LAST:event_menuIAltaActionPerformed

    private void menuIDispersionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuIDispersionActionPerformed
        // TODO add your handling code here:
        fDisp = new frmCDispersion();
        fDisp.setDefaultCloseOperation(frmCDispersion.DISPOSE_ON_CLOSE);
        fDisp.setVisible(true);
    }//GEN-LAST:event_menuIDispersionActionPerformed

    private void menuINuevosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuINuevosActionPerformed
        // TODO add your handling code here:
        fNew = new frmReportesRH(this,false);
        fNew.setDefaultCloseOperation(frmReportesRH.DISPOSE_ON_CLOSE);
        fNew.setVisible(true);
    }//GEN-LAST:event_menuINuevosActionPerformed

    private void menuCalendarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCalendarioActionPerformed
        // TODO add your handling code here:
        frmAltaCalendarioProc fCalendario = new frmAltaCalendarioProc(this,false);
        fCalendario.setDefaultCloseOperation(frmAltaCalendarioProc.DISPOSE_ON_CLOSE);
        fCalendario.setVisible(true);
    }//GEN-LAST:event_menuCalendarioActionPerformed

    private void menuMonitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMonitorActionPerformed
        // TODO add your handling code here:
        frmReporteDirector fCalendario = new frmReporteDirector(this,false);
        fCalendario.setDefaultCloseOperation(frmReporteDirector.DISPOSE_ON_CLOSE);
        fCalendario.setVisible(true);        
    }//GEN-LAST:event_menuMonitorActionPerformed

    private void menuCapturadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCapturadosActionPerformed
        // TODO add your handling code here:
        frmReporteDiario fCalendario = new frmReporteDiario(this,false);
        fCalendario.setDefaultCloseOperation(frmReporteDiario.DISPOSE_ON_CLOSE);
        fCalendario.setVisible(true);  
    }//GEN-LAST:event_menuCapturadosActionPerformed

    private void menuAportacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAportacionesActionPerformed
        // TODO add your handling code here:
        frmSubirReporteAportaciones fCalendario = new frmSubirReporteAportaciones(this,false);
        fCalendario.setDefaultCloseOperation(frmSubirReporteAportaciones.DISPOSE_ON_CLOSE);
        fCalendario.setVisible(true);         
    }//GEN-LAST:event_menuAportacionesActionPerformed

    private void menuIConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuIConsultaActionPerformed
        // TODO add your handling code here:
        frmEstadoCredito fECredito = new frmEstadoCredito(this,false);
        fECredito .setDefaultCloseOperation(frmEstadoCredito.DISPOSE_ON_CLOSE);
        fECredito .setVisible(true);       
    }//GEN-LAST:event_menuIConsultaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuAportaciones;
    private javax.swing.JMenuItem menuCalendario;
    private javax.swing.JMenu menuCapturaC;
    private javax.swing.JMenuItem menuCapturados;
    private javax.swing.JMenu menuContabilidad;
    private javax.swing.JMenuItem menuIAfectaciones;
    private javax.swing.JMenuItem menuIAlta;
    private javax.swing.JMenuItem menuIBaja;
    private javax.swing.JMenuItem menuICambio;
    private javax.swing.JMenuItem menuIConsulta;
    private javax.swing.JMenuItem menuIDispersion;
    private javax.swing.JMenuItem menuINuevos;
    private javax.swing.JMenuItem menuMonitor;
    private javax.swing.JMenu menuReportes;
    // End of variables declaration//GEN-END:variables
}
