/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import creditospce.credito;
import creditospce.creditoReporte;
import creditospce.dependencias;
import creditospce.qnaDependencias;
import creditospce.reporteNuevosCreditos;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Juan
 */
public class frmReportesRH extends javax.swing.JDialog {
    private int Dependencia=99;
    private int Quincena;
    private Date FIniProc;
    private Date FFinProc;
    private creditoReporte[] ACreditos = null;
    private DefaultTableModel modelo;
    //private String[] encabezados = {"","","","","",""}; 
    /**
     * Creates new form frmReportesRH
     */
    public frmReportesRH(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setModal(false);
        modelo = new DefaultTableModel(); 
        modelo.addColumn("DEPENDENCIA");
        modelo.addColumn("CREDITO");
        modelo.addColumn("F. CAPTURA");
        modelo.addColumn("F. DISPERSIÓN");
        modelo.addColumn("MONTO");
        modelo.addColumn("APORTACIÓN x Q.");
        //modelo.addColumn(encabezados);
        tableReporte.setModel(modelo);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTabla = new javax.swing.JPanel();
        pnlBotones = new javax.swing.JPanel();
        btnBuscar = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();
        pnlControles = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbxDependencia = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        cbxQuincena = new javax.swing.JComboBox();
        cbxPeriodo = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        chosserFInicio = new datechooser.beans.DateChooserCombo();
        jLabel5 = new javax.swing.JLabel();
        chosserFFin = new datechooser.beans.DateChooserCombo();
        pnlTitulo = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        scrollpTablaReporte = new javax.swing.JScrollPane();
        tableReporte = new javax.swing.JTable();
        labelNumeroCreditos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("MÓDULO DE REPORTES DE NUEVOS CREDITOS ");
        setBackground(new java.awt.Color(0, 153, 0));
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(936, 700));
        setResizable(false);

        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnImprimir.setText("IMPRIMIR");
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBotonesLayout = new javax.swing.GroupLayout(pnlBotones);
        pnlBotones.setLayout(pnlBotonesLayout);
        pnlBotonesLayout.setHorizontalGroup(
            pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBotonesLayout.createSequentialGroup()
                .addContainerGap(204, Short.MAX_VALUE)
                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(btnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(259, 259, 259))
        );
        pnlBotonesLayout.setVerticalGroup(
            pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotonesLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlTablaLayout = new javax.swing.GroupLayout(pnlTabla);
        pnlTabla.setLayout(pnlTablaLayout);
        pnlTablaLayout.setHorizontalGroup(
            pnlTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTablaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlTablaLayout.setVerticalGroup(
            pnlTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTablaLayout.createSequentialGroup()
                .addComponent(pnlBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 31, Short.MAX_VALUE))
        );

        jLabel1.setText("Dependencia:");

        cbxDependencia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "TODOS", "PODER EJECUTIVO", "PODER LEGISLATIVO", "PODER JUDICIAL", "MAGISTERIO", "JUBILADOS Y PENSIONADOS", "PENSIONES CIVILES DEL ESTADO DE TLAXCALA", "MUNICIPIO DE TLAXCALA", "MUNICIPIO DE CHIAUTEMPAN", "MUNICIPIO DE APETATITLAN", "CAPAM", "DIF TLAXCALA", "MUNICIPIO JUAN CUAMATZI", "MUNICIPIO DE TEPEYANCO", "MUNICIPO DE ANTONIO CARBAJAL" }));
        cbxDependencia.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxDependenciaItemStateChanged(evt);
            }
        });

        jLabel2.setText("Quincena:");

        cbxQuincena.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24" }));
        cbxQuincena.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxQuincenaItemStateChanged(evt);
            }
        });

        cbxPeriodo.setText("Periodo");
        cbxPeriodo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxPeriodoItemStateChanged(evt);
            }
        });

        jLabel4.setText("F. Inicio:");

        chosserFInicio.setCurrentView(new datechooser.view.appearance.AppearancesList("Bordered",
            new datechooser.view.appearance.ViewAppearance("custom",
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    true,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 255),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(128, 128, 128),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(255, 0, 0),
                    false,
                    false,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                (datechooser.view.BackRenderer)null,
                false,
                true)));
    chosserFInicio.setEnabled(false);
    chosserFInicio.addCommitListener(new datechooser.events.CommitListener() {
        public void onCommit(datechooser.events.CommitEvent evt) {
            chosserFInicioOnCommit(evt);
        }
    });

    jLabel5.setText("F.Fin:");

    chosserFFin.setCurrentView(new datechooser.view.appearance.AppearancesList("Bordered",
        new datechooser.view.appearance.ViewAppearance("custom",
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                new java.awt.Color(0, 0, 0),
                new java.awt.Color(0, 0, 255),
                false,
                true,
                new datechooser.view.appearance.swing.ButtonPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                new java.awt.Color(0, 0, 0),
                new java.awt.Color(0, 0, 255),
                true,
                true,
                new datechooser.view.appearance.swing.ButtonPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                new java.awt.Color(0, 0, 255),
                new java.awt.Color(0, 0, 255),
                false,
                true,
                new datechooser.view.appearance.swing.ButtonPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                new java.awt.Color(128, 128, 128),
                new java.awt.Color(0, 0, 255),
                false,
                true,
                new datechooser.view.appearance.swing.LabelPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                new java.awt.Color(0, 0, 0),
                new java.awt.Color(0, 0, 255),
                false,
                true,
                new datechooser.view.appearance.swing.LabelPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                new java.awt.Color(0, 0, 0),
                new java.awt.Color(255, 0, 0),
                false,
                false,
                new datechooser.view.appearance.swing.ButtonPainter()),
            (datechooser.view.BackRenderer)null,
            false,
            true)));
chosserFFin.setEnabled(false);
chosserFFin.addCommitListener(new datechooser.events.CommitListener() {
    public void onCommit(datechooser.events.CommitEvent evt) {
        chosserFFinOnCommit(evt);
    }
    });

    javax.swing.GroupLayout pnlControlesLayout = new javax.swing.GroupLayout(pnlControles);
    pnlControles.setLayout(pnlControlesLayout);
    pnlControlesLayout.setHorizontalGroup(
        pnlControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(pnlControlesLayout.createSequentialGroup()
            .addGap(32, 32, 32)
            .addGroup(pnlControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel1)
                .addComponent(cbxPeriodo))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(pnlControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlControlesLayout.createSequentialGroup()
                    .addComponent(jLabel4)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(chosserFInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(3, 3, 3)
                    .addComponent(jLabel5)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(chosserFFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(282, Short.MAX_VALUE))
                .addGroup(pnlControlesLayout.createSequentialGroup()
                    .addComponent(cbxDependencia, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(cbxQuincena, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(68, 68, 68))))
    );
    pnlControlesLayout.setVerticalGroup(
        pnlControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(pnlControlesLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(pnlControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1)
                .addComponent(cbxDependencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel2)
                .addComponent(cbxQuincena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
            .addGroup(pnlControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxPeriodo)
                    .addComponent(jLabel4))
                .addGroup(pnlControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(chosserFInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chosserFFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap())
    );

    jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
    jLabel3.setText("REPORTE DE NUEVOS CREDITOS");

    javax.swing.GroupLayout pnlTituloLayout = new javax.swing.GroupLayout(pnlTitulo);
    pnlTitulo.setLayout(pnlTituloLayout);
    pnlTituloLayout.setHorizontalGroup(
        pnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTituloLayout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel3)
            .addGap(207, 207, 207))
    );
    pnlTituloLayout.setVerticalGroup(
        pnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTituloLayout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel3)
            .addGap(24, 24, 24))
    );

    tableReporte.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null}
        },
        new String [] {
            "Dependencia", "Credito", "Fecha de Captura", "Fecha de Dispersión", "Monto", "Aportación Q."
        }
    ));
    scrollpTablaReporte.setViewportView(tableReporte);

    labelNumeroCreditos.setText("NUMERO DE CREDITOS ENCONTRADOS:        ");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(23, 23, 23)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(pnlTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(pnlControles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(pnlTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(scrollpTablaReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createSequentialGroup()
                    .addGap(210, 210, 210)
                    .addComponent(labelNumeroCreditos, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap(18, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(pnlTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(23, 23, 23)
            .addComponent(pnlControles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(scrollpTablaReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
            .addComponent(labelNumeroCreditos)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(pnlTabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap())
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxPeriodoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxPeriodoItemStateChanged
        // TODO add your handling code here:
            modelo.setRowCount(0);
            if (cbxPeriodo.isSelected())
            {
                chosserFFin.setEnabled(true);
                chosserFInicio.setEnabled(true);
                //cbxPeriodo.setEnabled(false);
                Quincena=0;
            }
            if (cbxPeriodo.isSelected()==false)
            {
                chosserFFin.setEnabled(false);
                chosserFInicio.setEnabled(false);
                //cbxPeriodo.setEnabled(true);
            }
        
    }//GEN-LAST:event_cbxPeriodoItemStateChanged

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        credito CReportar;
        int Estatus=5;
        int NCreditos=0;
        CReportar = new credito();
        creditoReporte[] creditosReportar = null;
        //limpiamos tabla
        modelo.setRowCount(0);
        //se selecciono Todas las Dependencias

        //Determina si se selecciona por periodo o por Quincena
        if (cbxPeriodo.isSelected()==false)
        {
            Quincena=cbxQuincena.getSelectedIndex()+1;
        }
        if((Quincena!=0)&&(Dependencia!=99))
        {
            qnaDependencias CDependencia;
            CDependencia = new qnaDependencias();
            FIniProc=CDependencia.getFIniProc(Dependencia,Quincena);
            FFinProc=CDependencia.getFFinProc(Dependencia,Quincena); 
        }
        SimpleDateFormat sdf=new java.text.SimpleDateFormat("dd/MM/yyyy");   
        //obtiene nuevo creditos
        creditosReportar=CReportar.consultaCreditosReporteNuevosC(Estatus,Dependencia,FIniProc,FFinProc);
        //llena la JTable con la consulta de los creditos a reportar por dependencia
        NCreditos=creditosReportar.length;
        Object datos[]=new Object[6];
        String cveCredito=" ";
        labelNumeroCreditos.setText("NUMERO DE CREDITOS ENCONTRADOS: "+Integer.toString(NCreditos) );
        for (int i=0; i<NCreditos; i++)
        {
            
            //sector - dependencia
            datos[0]=creditosReportar[i].IdSector;
            //clave de credito
            if (creditosReportar[i].IdCredito==0) {cveCredito="V-";}
            if (creditosReportar[i].IdCredito==1) {cveCredito="R-";}
            if (creditosReportar[i].IdCredito==2) {cveCredito="H-";}
            cveCredito=cveCredito+String.valueOf(creditosReportar[i].ano)+"-"+String.valueOf(creditosReportar[i].NCredito);
            datos[1]=cveCredito;
            //fecha de captura
            datos[2]=sdf.format(creditosReportar[i].FCaptura);
            //fecha de dispersión
            datos[3]=sdf.format(creditosReportar[i].FDispercion); 
            //Monto del credito
            datos[4]=creditosReportar[i].Montoa;
            //Retención Quincenal
            datos[5]=creditosReportar[i].Aportacion;     
            modelo.addRow(datos);
        }
        
        
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void chosserFInicioOnCommit(datechooser.events.CommitEvent evt) {//GEN-FIRST:event_chosserFInicioOnCommit
        // TODO add your handling code here:
        FIniProc= chosserFInicio.getCurrent().getTime();
    }//GEN-LAST:event_chosserFInicioOnCommit

    private void chosserFFinOnCommit(datechooser.events.CommitEvent evt) {//GEN-FIRST:event_chosserFFinOnCommit
        // TODO add your handling code here:
        FFinProc=chosserFFin.getCurrent().getTime();
    }//GEN-LAST:event_chosserFFinOnCommit

    private void cbxQuincenaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxQuincenaItemStateChanged
        // TODO add your handling code here:
        Quincena=cbxQuincena.getSelectedIndex()+1;
        modelo.setRowCount(0);
    }//GEN-LAST:event_cbxQuincenaItemStateChanged

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        // TODO add your handling code here:
        //imprime el reporte segun la dependencia q lo solicita
        //se envia Dependencia, fecha inicio FInicio y fecha fin FFin
                reporteNuevosCreditos repNuevosCreditos = new reporteNuevosCreditos(Dependencia,FIniProc,FFinProc);
                try {
                    repNuevosCreditos.generaSolicitud();
                } 
                catch (Exception ex) {
                    Logger.getLogger(capturaCredito.class.getName()).log(Level.SEVERE, null, ex);
                }        
        
    }//GEN-LAST:event_btnImprimirActionPerformed

    private void cbxDependenciaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxDependenciaItemStateChanged
        // TODO add your handling code here:
        String SDependencia;
        dependencias cgDependencias=new dependencias();
        modelo.setRowCount(0);
        if (cbxDependencia.getSelectedIndex()==0)
        {
            Dependencia=99;
        }
        else
        {
            SDependencia=cbxDependencia.getSelectedItem().toString();
            Dependencia=cgDependencias.IdDependencia(SDependencia);
        }
    }//GEN-LAST:event_cbxDependenciaItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmReportesRH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmReportesRH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmReportesRH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmReportesRH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmReportesRH dialog = new frmReportesRH(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JComboBox cbxDependencia;
    private javax.swing.JCheckBox cbxPeriodo;
    private javax.swing.JComboBox cbxQuincena;
    private datechooser.beans.DateChooserCombo chosserFFin;
    private datechooser.beans.DateChooserCombo chosserFInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel labelNumeroCreditos;
    private javax.swing.JPanel pnlBotones;
    private javax.swing.JPanel pnlControles;
    private javax.swing.JPanel pnlTabla;
    private javax.swing.JPanel pnlTitulo;
    private javax.swing.JScrollPane scrollpTablaReporte;
    private javax.swing.JTable tableReporte;
    // End of variables declaration//GEN-END:variables
}
