/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.text.NumberFormat;
import java.util.Locale;

/**
 *
 * @author Juan
 */
public class panelCalendario extends java.awt.Panel {

    /**
     * Creates new form panelCalendario
     */
    
    public panelCalendario(int NA, String QNA, Double MI, Double MF, Double AQ, Double AC, Double AI, Double AA ) {
        initComponents();
        NumberFormat n = NumberFormat.getCurrencyInstance(Locale.US);
        txtN.setText(String.valueOf(NA));
        txtAportacionCapital.setText(n.format(AC));
        txtAportacionInteres.setText(n.format(AC));
        txtApotacionQuincenal.setText(n.format(AC));
        txtMontoFinal.setText(n.format(AC));
        txtMontoInicial.setText(n.format(AC));
        txtQuincena.setText(QNA);
    }
    
    public double getPagoAdelantado()
    {
        Double PA=0.0;
        PA=Double.valueOf(txtPagoAdelantado.getText());
        return PA;
    }   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtQuincena = new javax.swing.JTextField();
        txtN = new javax.swing.JTextField();
        txtMontoInicial = new javax.swing.JTextField();
        txtApotacionQuincenal = new javax.swing.JTextField();
        txtAportacionCapital = new javax.swing.JTextField();
        txtPagoAdelantado = new javax.swing.JTextField();
        txtAportacionInteres = new javax.swing.JTextField();
        txtMontoFinal = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtQuincena.setEditable(false);
        add(txtQuincena, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 63, -1));

        txtN.setEditable(false);
        add(txtN, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 28, -1));

        txtMontoInicial.setEditable(false);
        add(txtMontoInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 118, -1));

        txtApotacionQuincenal.setEditable(false);
        add(txtApotacionQuincenal, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 118, -1));

        txtAportacionCapital.setEditable(false);
        add(txtAportacionCapital, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 118, -1));

        txtPagoAdelantado.setText("0");
        txtPagoAdelantado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPagoAdelantadoKeyTyped(evt);
            }
        });
        add(txtPagoAdelantado, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, 118, -1));

        txtAportacionInteres.setEditable(false);
        add(txtAportacionInteres, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, 118, -1));

        txtMontoFinal.setEditable(false);
        add(txtMontoFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 10, 118, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtPagoAdelantadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPagoAdelantadoKeyTyped
        // TODO add your handling code here:
        //solo acepta numeros y el simbolo "." como separador
        char caracter = evt.getKeyChar();
        if (!Character.isDigit(caracter))
        {
            if (caracter!='.')
            {
                getToolkit().beep();
                evt.consume();            
            }
        }        
    }//GEN-LAST:event_txtPagoAdelantadoKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField txtAportacionCapital;
    private javax.swing.JTextField txtAportacionInteres;
    private javax.swing.JTextField txtApotacionQuincenal;
    private javax.swing.JTextField txtMontoFinal;
    private javax.swing.JTextField txtMontoInicial;
    private javax.swing.JTextField txtN;
    private javax.swing.JTextField txtPagoAdelantado;
    private javax.swing.JTextField txtQuincena;
    // End of variables declaration//GEN-END:variables
}
