/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author Juan
 */
public class panelTotalesCredito extends javax.swing.JPanel {

    /**
     * Creates new form panelTotalesCredito
     */
    public panelTotalesCredito() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTotalHipotecarios1 = new javax.swing.JTextField();
        txtTotalRojos1 = new javax.swing.JTextField();
        txtTotalVerdes1 = new javax.swing.JTextField();
        txtTotalVerdes = new javax.swing.JTextField();
        txtTotalRojos = new javax.swing.JTextField();
        txtTotalHipotecarios = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelTitulo = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(499, 105));
        setMinimumSize(new java.awt.Dimension(499, 105));

        txtTotalHipotecarios1.setEditable(false);
        txtTotalHipotecarios1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalHipotecarios1ActionPerformed(evt);
            }
        });

        txtTotalRojos1.setEditable(false);
        txtTotalRojos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalRojos1ActionPerformed(evt);
            }
        });

        txtTotalVerdes1.setEditable(false);

        txtTotalVerdes.setEditable(false);

        txtTotalRojos.setEditable(false);
        txtTotalRojos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalRojosActionPerformed(evt);
            }
        });

        txtTotalHipotecarios.setEditable(false);
        txtTotalHipotecarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalHipotecariosActionPerformed(evt);
            }
        });

        jLabel4.setText("CREDITOS HIPOTECARIOS");

        jLabel3.setText("CREDITOS ROJOS");

        jLabel2.setText("CREDITOS VERDES");

        labelTitulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelTitulo.setText("TOTAL DE CREDITOS OTORGADOS EN EL AÑO EN CURSO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtTotalVerdes1)
                                .addComponent(txtTotalVerdes, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3)
                            .addComponent(txtTotalRojos1, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                            .addComponent(txtTotalRojos))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(txtTotalHipotecarios, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTotalHipotecarios1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotalRojos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotalHipotecarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotalVerdes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotalVerdes1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotalRojos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotalHipotecarios1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtTotalHipotecarios1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalHipotecarios1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalHipotecarios1ActionPerformed

    private void txtTotalRojos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalRojos1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalRojos1ActionPerformed

    private void txtTotalRojosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalRojosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalRojosActionPerformed

    private void txtTotalHipotecariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalHipotecariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalHipotecariosActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public javax.swing.JLabel labelTitulo;
    public javax.swing.JTextField txtTotalHipotecarios;
    public javax.swing.JTextField txtTotalHipotecarios1;
    public javax.swing.JTextField txtTotalRojos;
    public javax.swing.JTextField txtTotalRojos1;
    public javax.swing.JTextField txtTotalVerdes;
    public javax.swing.JTextField txtTotalVerdes1;
    // End of variables declaration//GEN-END:variables
}
