/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import vista.frmCreditoBanco;
import java.awt.Color;
import java.util.Date;

/**
 *
 * @author Juan
 */
public class PestatusCredito extends javax.swing.JPanel {
    private int TIPOCREDITO;
    private int ANO;
    private int NCREDITO;
    private double MONTOSOLICITADO;
    private String PATERNO;
    private String MATERNO;
    private String NOMBRE;
    private Date FSOLICITUD;
    private Date FAPROBACION;
    private int IDEMPLEADO;

    

    /**
     * Creates new form PestatusCredito
     */
    public PestatusCredito() {
        initComponents();
        TIPOCREDITO=0;
        ANO=0;
        NCREDITO=0;
        MONTOSOLICITADO=0;
        PATERNO="";
        MATERNO="";
        NOMBRE="";
        Date fecha = new Date();
        FSOLICITUD=fecha;
        FAPROBACION=fecha;
        
        String cvecredito="";
        if (TIPOCREDITO==0){cvecredito="V-";}
        if (TIPOCREDITO==1){cvecredito="R-";}
        if (TIPOCREDITO==2){cvecredito="H-";}
        cvecredito=cvecredito+String.valueOf(ANO)+"-"+String.format("%05d",NCREDITO);
        txtCVECredito.setText(cvecredito);
        txtEmpleado.setText(NOMBRE+" "+PATERNO+" "+MATERNO);
        txtMonto.setText(Double.toString(MONTOSOLICITADO));
        java.text.SimpleDateFormat sdf=new java.text.SimpleDateFormat("dd/MM/yyyy");
        txtFCaptura.setText(sdf.format(FSOLICITUD));
        txtFAprobacion.setText(sdf.format(FAPROBACION));        
    }

    public PestatusCredito(int id, int tc, int a, int nc, double mto, String p, String m, String n, Date fd, Date fa) {
        initComponents();
        IDEMPLEADO=id;
        TIPOCREDITO=tc;
        ANO=a;
        NCREDITO=nc;
        MONTOSOLICITADO=mto;
        PATERNO=p;
        MATERNO=m;
        NOMBRE=n;
        FSOLICITUD=fd;
        FAPROBACION=fa;
        
        String cvecredito="";
        if (TIPOCREDITO==0)
        {
            cvecredito="V-";
            this.setBackground(Color.GREEN);
        }
        if (TIPOCREDITO==1)
        {
            cvecredito="R-";
            this.setBackground(Color.RED);
        }
        if (TIPOCREDITO==2)
        {
            cvecredito="H-";
            this.setBackground(Color.YELLOW);
        }
        cvecredito=cvecredito+String.valueOf(ANO)+"-"+String.format("%05d",NCREDITO);
        txtCVECredito.setText(cvecredito);
        txtEmpleado.setText(NOMBRE+" "+PATERNO+" "+MATERNO);
        txtMonto.setText(Double.toString(MONTOSOLICITADO));
        java.text.SimpleDateFormat sdf=new java.text.SimpleDateFormat("dd/MM/yyyy");
        txtFCaptura.setText(sdf.format(FSOLICITUD));
        txtFAprobacion.setText(sdf.format(FAPROBACION));
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCVECredito = new javax.swing.JTextField();
        txtEmpleado = new javax.swing.JTextField();
        txtMonto = new javax.swing.JTextField();
        txtFCaptura = new javax.swing.JTextField();
        txtFAprobacion = new javax.swing.JTextField();

        setMaximumSize(new java.awt.Dimension(973, 31));
        setMinimumSize(new java.awt.Dimension(973, 31));

        txtCVECredito.setEditable(false);
        txtCVECredito.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCVECreditoMouseClicked(evt);
            }
        });

        txtEmpleado.setEditable(false);

        txtMonto.setEditable(false);

        txtFCaptura.setEditable(false);

        txtFAprobacion.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtCVECredito, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtFCaptura, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtFAprobacion, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCVECredito)
                    .addComponent(txtEmpleado)
                    .addComponent(txtMonto)
                    .addComponent(txtFCaptura)
                    .addComponent(txtFAprobacion)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtCVECreditoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCVECreditoMouseClicked
        // TODO add your             
        frmCreditoBanco NCBanco0;         
        int nclicks;
        nclicks=evt.getClickCount();
        if (nclicks==2)
        {
            NCBanco0 = new frmCreditoBanco(null,true);  
            NCBanco0.setCredito(IDEMPLEADO,TIPOCREDITO,ANO,NCREDITO);
            NCBanco0.setVisible(true);   
            if(NCBanco0.getFlag())
            {
                this.setBackground(Color.gray);
                NCBanco0.cierra();
            }
            
            
        }
    }//GEN-LAST:event_txtCVECreditoMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField txtCVECredito;
    private javax.swing.JTextField txtEmpleado;
    private javax.swing.JTextField txtFAprobacion;
    private javax.swing.JTextField txtFCaptura;
    private javax.swing.JTextField txtMonto;
    // End of variables declaration//GEN-END:variables
}
